build-job:
  stage: build
  image: alpine:latest 
  script:
    - apk update
    - apk add clang make compiler-rt
    - echo "Test du Makefile"
    - make all
    - if [ -f "main_tui.o" ]; then echo "Makefile is compiling."; else echo "main_tui.o not found. " && exit 1; fi
    - make clean
    - if [ -f "main_tui.o" ]; then echo "Makefile is not cleaning well."&& exit 1; else echo "Makefile is cleaning well. "; fi
  only:
    - dev
    

test-job1:
  stage: test
  script:
    - echo "Job exemple qui va verifier que il existe bien un fichier main_tui.c "
    - if [ -f "main_tui.c" ]; then echo "main_tui.c exists"; else echo "main_tui.c not found" && exit 1; fi
  only:
    - dev

test-job-player:
  stage: test
  image: alpine:latest
  script:
    - apk update
    - apk add bash make compiler-rt
    - make all 
    - echo "Début du test du modèle player."
    - OUTPUT=$(make run_test_player 2>&1)
    - echo "$OUTPUT"
    - LAST_LINE=$(echo "$OUTPUT" | tail -n 1)
    - if echo "$LAST_LINE" | grep -q "La librairie player passe tout les tests"; then
        echo "Test réussi! La librairie player passe tous les tests.";
      else
        echo "Test échoué! La dernière ligne ne contient pas le message attendu.";
        exit 1;
      fi
  only:
    - dev